import AuthGuard from "@/components/AuthGuard";
import CanvasClient from "./CanvasClient";

export default function Page() {
  return (
    <AuthGuard>
      <CanvasClient />
    </AuthGuard>
  );
}





/* 
Test database details:
DATABASE_URL="postgresql://postgres:Abvgiet@keshu1@db.litqhdkppyvirkthadgw.supabase.co:5432/postgres?sslmode=require"
SUPABASE_SERVICE_ROLE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpdHFoZGtwcHl2aXJrdGhhZGd3Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2ODgzMzk4MiwiZXhwIjoyMDg0NDA5OTgyfQ.M9TDqvlPntQzVcS65m93tQaPI7swIsOcbwNeTuTOJGc"
NEXT_PUBLIC_SUPABASE_URL=https://litqhdkppyvirkthadgw.supabase.co
NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpdHFoZGtwcHl2aXJrdGhhZGd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg4MzM5ODIsImV4cCI6MjA4NDQwOTk4Mn0.T58fpbjDArECq4LsljYFUkpDALMw7zUpAM_m7JJm-yc
SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpdHFoZGtwcHl2aXJrdGhhZGd3Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2ODgzMzk4MiwiZXhwIjoyMDg0NDA5OTgyfQ.M9TDqvlPntQzVcS65m93tQaPI7swIsOcbwNeTuTOJGc


prod database details:
DATABASE_URL="postgresql://postgres:Abvgiet@keshu1@db.vujpuxhopvhbqgusvoum.supabase.co:5432/postgres?sslmode=require"
SUPABASE_SERVICE_ROLE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1anB1eGhvcHZoYnFndXN2b3VtIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2ODMyNzE2OSwiZXhwIjoyMDgzOTAzMTY5fQ.Osi79EekwxIFGOUoWL2r55oZ9sAoLZgKmykd6JYOJvs"
NEXT_PUBLIC_SUPABASE_URL=https://vujpuxhopvhbqgusvoum.supabase.co
NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1anB1eGhvcHZoYnFndXN2b3VtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgzMjcxNjksImV4cCI6MjA4MzkwMzE2OX0.RYW9FjMmKtK26eYNVgW_3qkzTHR7_e3vHTEqJIGiwXA
SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1anB1eGhvcHZoYnFndXN2b3VtIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2ODMyNzE2OSwiZXhwIjoyMDgzOTAzMTY5fQ.Osi79EekwxIFGOUoWL2r55oZ9sAoLZgKmykd6JYOJvs
*/

